<?php

return [
    'HOMEPAGE' => '首页',
    'LDTDFMS'  => 'LDTDF 任务流管理系统',
    'USER_PROFILE' => '个人信息',
    'USER_LOGIN'   => '用户登录',
    'USER_LOGOUT'  => '退出登录',
    'SWITCH_LANG'  => '切换语言',
    'ACCOUNT'  => '账户',
    'PASSWORD' => '密码',
    'PASSWORD_NEW' => '新密码',
    'PASSWORD_OLD' => '原密码',
    'PROVIDE_OLD_PASSWD' => '请输入原密码',
    'PROVIDE_NEW_PASSWD' => '请输入新密码',
    'EMAIL' => '邮箱',
    'ADMIN' => '管理员',
    'PROJECT_MANAGER' => '产品经理',
    'DEVELOPER' => '开发者',
    'TESTER' => '测试人员',
    'SIGN_IN'  => '登录',
    'NO_USER'  => '用户不存在',
    'ILLEGAL_USER_CREDENTIALS' => '非法用户',
    'ILLEGAL_OLD_PASSWD' => '原密码错误',
    'UPDATE' => '更新',
    'UPDATED_OK' => '更新成功',
    'UPDATE_FAILED' => '更新失败',
    'UPDATED_NOTHING' => '无更新项',
    'VIEW_PERMISSION_DENIED' => '抱歉，你无权查看本页面',
];
