#!/usr/bin/env php
<?php

// ------------------------------------
//     Command Line Interface Entry  
// ------------------------------------

require_once __DIR__.'/vendor/autoload.php';

$app = new Lif\Core\App;

print_r($argv);
