<?php

return [
    'HOMEPAGE' => 'Home',
    'LDTDFMS'  => 'LDTDF Taskflow Manage System',
    'USER_PROFILE' => 'Profile',
    'USER_LOGIN'   => 'Login',
    'USER_LOGOUT'  => 'Logout',
    'SWITCH_LANG'  => 'Switch Language',
    'ACCOUNT' => 'Account',
    'PASSWORD' => 'Password',
    'PASSWORD_NEW' => 'New Password',
    'PASSWORD_OLD' => 'Old Password',
    'PROVIDE_OLD_PASSWD' => 'Provide old password',
    'PROVIDE_NEW_PASSWD' => 'Provide new password',
    'EMAIL' => 'Email',
    'ADMIN' => 'Admin',
    'PROJECT_MANAGER' => 'Project Manager',
    'DEVELOPER' => 'Developer',
    'TESTER' => 'Tester',
    'SIGN_IN'  => 'Sign In',
    'NO_USER'  => 'User not found',
    'ILLEGAL_USER_CREDENTIALS' => 'Illegal user',
    'ILLEGAL_OLD_PASSWD' => 'Origin password mismatch',
    'UPDATE' => 'Update',
    'UPDATED_OK' => 'Updated Successfully',
    'UPDATE_FAILED' => 'Updated failed',
    'UPDATED_NOTHING' => 'Updated nothing',
    'VIEW_PERMISSION_DENIED' => 'You do not have permission to view this page',
];
